dist: trusty
sudo: require
language: cpp
compiler:
  - gcc
branches:
  only:
  - master
  - tr

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake

      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    #- sudo apt-get -qq update
    - sudo apt-get install -y libsfml-dev
    - eval "${MATRIX_EVAL}"

script:
    - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
    - gcc -v && g++ -v && cmake --version
    # Build it now
    - cmake CMakeLists.txt
    - make
    
notifications:
  email: false
