dist: trusty
sudo: require
language: cpp
compiler:
  - gcc

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libsfml-dev
    - eval "${MATRIX_EVAL}"

script:
    - gcc -v && g++ -v && cmake --version
    - cmake CMakeLists.txt
    - make
